//
// Generated file, do not edit! Created by nedtool 5.3 from src/AppJob.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __APPJOB_M_H
#define __APPJOB_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0503
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/AppJob.msg:11</tt> by nedtool.
 * <pre>
 * message AppJob
 * {
 *     //\@customize(true);
 *     int appId;					// ID of thc considered cloud App
 * }
 * </pre>
 */
class AppJob : public ::omnetpp::cMessage
{
  protected:
    int appId;

  private:
    void copy(const AppJob& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AppJob&);

  public:
    AppJob(const char *name=nullptr, short kind=0);
    AppJob(const AppJob& other);
    virtual ~AppJob();
    AppJob& operator=(const AppJob& other);
    virtual AppJob *dup() const override {return new AppJob(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getAppId() const;
    virtual void setAppId(int appId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AppJob& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AppJob& obj) {obj.parsimUnpack(b);}


#endif // ifndef __APPJOB_M_H

